[package]
name = "ferrule-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "ferrule"
path = "src/main.rs"

[features]
default = ["ferrule-core/postgres", "ferrule-core/mysql", "ferrule-core/mssql", "ferrule-core/sqlite"]
all = ["ferrule-core/oracle", "ferrule-core/ssh"]
oracle = ["ferrule-core/oracle"]
ssh = ["ferrule-core/ssh"]

[dependencies]
ferrule-core = { path = "../ferrule-core" }
ferrule-config = { path = "../ferrule-config" }

clap = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
miette = { workspace = true }
is-terminal = { workspace = true }
secrecy = { workspace = true }
thiserror = { workspace = true }

chrono = { workspace = true }
crossterm = "0.28"
notify = "8"

rpassword = { workspace = true }
rustyline = "15"
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3"
jmespath = "0.5"
dashmap = "6"
dirs = { workspace = true }
indexmap = { workspace = true }
hasp = { path = "../../hasp/crates/hasp", default-features = false, features = ["env", "keyring", "file"] }
